# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotisation', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=False)),
                ('duree', models.IntegerField(default=5)),
                ('date_creation', models.DateTimeField(auto_now=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surnom', models.CharField(blank=True, max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('unrestricted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Forward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fournisseur', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(max_length=32, unique=True)),
                ('client', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Port', unique=True),
        ),
        migrations.AddField(
            model_name='forward',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fournisseur', unique=True),
        ),
        migrations.AddField(
            model_name='forward',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Port', unique=True),
        ),
        migrations.AddField(
            model_name='activation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client'),
        ),
        migrations.AddField(
            model_name='activation',
            name='fournisseur',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Fournisseur'),
        ),
    ]
