# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='nom',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
