# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170725_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='numero',
            field=models.CharField(max_length=100),
        ),
    ]
