# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170725_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='tcp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='port',
            name='udp',
            field=models.BooleanField(default=False),
        ),
    ]
