# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170725_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forward',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fournisseur'),
        ),
        migrations.AlterField(
            model_name='forward',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Port'),
        ),
        migrations.AlterField(
            model_name='input',
            name='fournisseur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fournisseur'),
        ),
        migrations.AlterField(
            model_name='input',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Port'),
        ),
    ]
