# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170725_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='server',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
