# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fournisseur_server'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fournisseur',
            new_name='Supplier',
        ),
        migrations.RenameField(
            model_name='activation',
            old_name='actif',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='activation',
            old_name='date_creation',
            new_name='creation',
        ),
        migrations.RenameField(
            model_name='activation',
            old_name='duree',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='activation',
            old_name='date_modification',
            new_name='modification',
        ),
        migrations.RenameField(
            model_name='activation',
            old_name='cotisation',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='activation',
            old_name='fournisseur',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='surnom',
            new_name='nickname',
        ),
        migrations.RenameField(
            model_name='forward',
            old_name='fournisseur',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='input',
            old_name='fournisseur',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='mac',
            old_name='adresse',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='numero',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='server',
            new_name='server_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='prenom',
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
