# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170725_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='creation',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='activation',
            name='modification',
            field=models.DateField(auto_now=True),
        ),
    ]
