# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170725_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='creation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
