# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170725_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='modification',
        ),
        migrations.AlterField(
            model_name='activation',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activation',
            name='subscription',
            field=models.IntegerField(default=25),
        ),
    ]
